### PR TITLE
chore: bump docusaurus to 5.6.2

### PR DESCRIPTION
**Pull request by mxschmitt**
Looks like `"@docusaurus/tsconfig": "3.6.2"` introduced a regression for us in https://github.com/facebook/docusaurus/commit/5344bc105e720ff6d2b588bcd1568eb71e957148 where we had to add it manually back. Without that it ended up in:

```
src/pages/versions.tsx:22:7 - error TS2322: Type '{ children: Element; title: string; description: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'title' does not exist on type 'IntrinsicAttributes & Props'.

22       title="Versions"
         ~~~~~
```

cc @slorber

### CODE REVIEW

**Review by debs-obrien — APPROVED** [review]

File: tsconfig.json [hunk 1]
```diff
@@ -1,12 +1,15 @@
...
     "compilerOptions": {
       "baseUrl": ".",
       "downlevelIteration": true,
-      "moduleResolution": "Node16",
-      "module": "Node16"
+      "types": [
+        "node",
+        "@docusaurus/module-type-aliases",
+        "@docusaurus/theme-classic"
+      ],
```
Comment (slorber) [inline tsconfig.json:13]: You probably don't need to restore this

If you import the preset types in your config file (making your TS config more typesafe), then the required ambient types gets registered as well.

See also: https://github.com/facebook/docusaurus/issues/10733#issuecomment-2520939228

Comment (mxschmitt) [reply tsconfig.json:13]: Thank you!
